//LEMBRE-SE QUE : uma classe deve possuir a primeira letra UpperCase e o nome do arquivo java precisa ser identico ao da classe


/*Usando várias classes
Você também pode criar um objeto de uma classe e acessá-lo em outra classe. Isso é freqüentemente usado para melhor organização das classes (uma classe possui todos os atributos e métodos, enquanto a outra classe contém o método main () (código a ser executado)).

Lembre-se de que o nome do arquivo java deve corresponder ao nome da classe. Neste exemplo, criamos dois arquivos no mesmo diretório / pasta:
*/
Main.java
Second.java

/*Remember that..
The dot (.) is used to access the object's attributes and methods.

To call a method in Java, write the method name followed by a set of parentheses (), followed by a semicolon (;).

A class must have a matching filename (Main and Main.java).*/
